title: Delia Li - Technical Writer
description: Welcome to my technical writing portfolio!
theme: just-the-docs
color_scheme: dark

url: https://delia-li.github.io/technical-writer/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: true
# defaults:
#   -
#     scope:
#       path: "projects"
#       type: "pages"
#     values:
#       layout: "project"
#       author: "Mr. Hyde"
#       category: "project"