title: Delia Li - Technology Writer
description: Welcome to my technical writing portfolio!
theme: just-the-docs
color_scheme: dark

url: https://delia-li.github.io/technical-writer/

search_enabled: true
